version: '3.5'

services:
  nuxt:
    container_name: nuxt_${PROJECT_NAME}
    build:
      context: ./${PROJECT_NAME}
    volumes:
      - ./${PROJECT_NAME}:/usr/src/${PROJECT_NAME}:rw,cached
      - /usr/src/${PROJECT_NAME}/node_modules
    ports:
      - '85:3000'